const express = require('express')
const router = express.Router()
const URL = require('../model/urlmodel');
const { restrictTo } = require('../middleware/auth');

//admin can see all the urls
router.get('/admin/urls', restrictTo(['ADMIN']) , async (req, res) => {

    //urls that are generated by a logged in user only
    const allUrls = await URL.find({})
    // console.log(allUrls)
    return res.render("home", {urls: allUrls})
})

router.get('/', restrictTo(['USER', 'ADMIN']) , async (req, res) => {

    //agar koi user logged in nhi hai toh login page pe redirect karo
    // if (!req.user) return res.redirect('/login');

    //urls that are generated by a logged in user only
    const allUrls = await URL.find({ createdBy: req.user._id})
    // console.log(allUrls)
    return res.render("home", {urls: allUrls})
})

router.get('/signup', (req, res) => {
    res.render("signup")
})
router.get('/login', (req, res) => {
    res.render("login")
})

module.exports = router